project_name: trellis-cyberduck
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/itinerisltd/trellis-cyberduck/cmd.version={{ .Version }}
    goos:
      - darwin
archives:
  - replacements:
      darwin: Darwin
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request #'
      - "^Merge branch '"
brews:
  - tap:
      owner: itinerisltd
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/ItinerisLtd/trellis-cyberduck
    description: Trellis commands for Cyberduck
    license: MIT
    install: |
      bin.install "trellis-cyberduck"
    test: |
      system "#{bin}/trellis-cyberduck --version"
release:
  prerelease: auto
