version: 2.1

orbs:
  go: circleci/go@1

jobs:
  test:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - run: go version
      - checkout
      - go/mod-download-cached
      - go/test:
          short: true
          verbose: true

  release:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - run: go version
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
      - store_artifacts:
          path: dist/

  release-dry-run:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - run: go version
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash -s check
      - run: curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist
      - store_artifacts:
          path: dist/

workflows:
  test:
    jobs:
      - test
      - release-dry-run
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
